### ISSUE TITLE
[WIP]bug: Unable to play video

### ISSUE THREAD

**Issue by intyouss** [toomanysource/atreus#105]
publish中minio外部ip填写错误，导致数据库存储ip为 minio:xxxx

**Comment by intyouss** [comment]
使用服务名进行连接docker机制，在当前的代码中无法灵活的分配minio访问ip，目前的方法只有，在publish config文件中固定书写外部服务器ip

**Comment by mo3et** [comment]
WIP.暂时用文档提示的方式解决 后续可改进

**Comment by intyouss** [comment]
此issue与 #122 重复，将关闭此issue
