### ISSUE TITLE
bug: Liked or Followed action, no update of user information

### ISSUE THREAD

**Issue by intyouss** [toomanysource/atreus#116]
点赞和关注之后，用户信息没有变化。原因是redis缓存没有更新

**Comment by alilestera** [comment]
Yes, you are right.

the methods of update user information should delete user cache from `redis` component.
the reason that do not update user full information is, cost more if request user full information from database.

I will create a PR to fix this issue.

**Comment by intyouss** [comment]
Looking forward to your work. Thank you.
