### ISSUE TITLE
bug: Failed to update cache information

### ISSUE THREAD

**Issue by intyouss** [toomanysource/atreus#119]
user个人信息缓存更新失败，redis无法正常更新。原因是创建删除缓存的goroutine方法没有正确放置

**Comment by intyouss** [comment]
```go
Where("id = ?", id).
Update("favorite_count", target).Error
})
if err != nil {
        go r.removeCache(DelayRemoveCache, id)
}
return err
```
`go r.removeCache(DelayRemoveCache, id)` ,this code should be raised `if err != nil`

**Comment by mo3et** [comment]
> ```go
> Where("id = ?", id).
> Update("favorite_count", target).Error
> })
> if err != nil {
>         go r.removeCache(DelayRemoveCache, id)
> }
> return err
> ```
> 
> `go r.removeCache(DelayRemoveCache, id)` ,this code should be raised `if err != nil`

`UpdateFollower` method in `user/data/user.go`?

**Comment by alilestera** [comment]
@intyouss thank you.

I will fix it.
